### PR TITLE
Support new team names

### LINKED ISSUE #462: Team Names not correct
### Sport

Football

### Summary

Seems like ESPN changed the location + nickname format for team names this year in fantasy football. Only a single team "name" now for team names. Output for each team is "Team" + <Last Name>. This is an issue for a family league where everyone has the same last name.

*Edit: This issue only impacts a team newly created this year (2023) with team names updated this year. Seems like an old league (no team names updated this year) displays the expected team names.

Updating line 8 in team.py 
from: self.team_name = "%s %s" % (data['location'], data['nickname'])
to:  self.team_name = data['name'])

### Logs/Data

Pulling data for a newly created 2023 league gave me following output for league.teams
[Team(Team Smith), Team(Team Smith), Team(Team Smith), Team(Team Smith), Team(Team Smith), Team(Team Smith), Team(Team Smith), Team(Team Smith)]

After updating the module with fix from above I now get the following output for league.teams
[Team(Cee Dee), Team(The Newts), Team(ÑFL), Team(So Hard), Team(Beavers), Team(Pabst Blue Ribbon), Team(The Bois), Team(Kyler Murray)]

### PR DESCRIPTION
**Pull request by dtcarls**
Fixes #462

### CODE REVIEW

**Comment by mkirby528** [comment]
@cwendt94 any change we could get this reviewed/merged before the start of the NFL season?

**Comment by cwendt94** [comment]
Yeah, I will have this in and publish changes today! Thanks for fixing this @dtcarls

**Comment by cwendt94** [comment]
@dtcarls @mkirby528 This fix should now be in version 0.31.0 `pip install espn-api==0.31.0`

**Comment by mkirby528** [comment]
Wonderful! Thank you both so much!

**Pull request merged**
