### PR TITLE
feat: Add standings_weekly method Football League Class

### PR DESCRIPTION
**Pull request by brthurr**
Method of the Football League class that will return a list of teams in the order of their standing for a current week. The method calculates the number of wins, losses, points for and points against from week 1 to the provided week. If no week is provided, it will calculate to the league.current_week.

Included test for the method as well.

### CODE REVIEW

**Comment by DesiPilla** [comment]
This would assume that `points_for` is the tiebreaker for all leagues. You can extract a league's explicit seeding order by
```
params = {
    'view': ['mSettings']
}
data = self.espn_request.league_get(params=params)
data["settings"]["scheduleSettings"]["playoffSeegingRule"]
```
assuming `self` is a `League` object. In your case, the tiebreaker should say `TOTAL_POINTS_SCORED`. I'm not sure the exact syntax for H2H tiebreakers.

**Comment by brthurr** [comment]
I have a question that may kill this PR. 

Any way of knowing if ESPN calculates points for and points against in real-time? For example, If I run standings on a Sunday at 3PM, will it return PF and PA up to 3 PM, taking into account the noon games that have already been played? Or does it wait for a weekly final, and it only will return PF and PA for the previous full week.

I want to test but won't be able to do so until Thursday when they actually play a game.

**Comment by brthurr** [comment]
For _my_ purposes, I want it to be static. I'm using it to determine standings at the end of the regular season (for our league, week 14) in order to populate my customer "losers bracket". I have code in my app that already determines if league.current_week is > 14. I was looking at this from the perspective of others who may want to use this method.

**Comment by DesiPilla** [comment]
@brthurr the tiebreaking process is quite complicated, but I took a stab at it [here](https://github.com/cwendt94/espn-api/pull/515).

**Comment by cwendt94** [comment]
@brthurr does @DesiPilla PR look to solve the weekly standings? If so we can close this one.

**Comment by brthurr** [comment]
@cwendt94, yep, this looks great! Thanks for the hard work, @DesiPilla! Closing PR.

**Pull request closed without merging**
